import "@/styles/globals.css";

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
